### PR TITLE
TOOL-666 #comment Added "test" type_tag to step.yml

### PR DESCRIPTION
**Pull request by richard-bogdan-bitrise**

### CODE REVIEW

**Comment by BirmacherAkos** [comment]
The PR is failing because it tries to download the go-lint from the old repo.
Solution:
Remove this from the Bitrise.yml
https://github.com/bitrise-steplib/steps-xamarin-android-test/blob/e7d8d0caa9c4304e6740885930381df1530cadf1/bitrise.yml#L77-L121

And add this to the ci workflow:
https://github.com/bitrise-steplib/steps-install-missing-android-tools/blob/master/bitrise.yml#L50-L53

It will use our "go steps" which have the updated locations

**Comment by BirmacherAkos** [comment]
And please do the maintenance for the bitrise.yml.

**Comment by richard-bogdan-bitrise** [comment]
Removed and updated bitrise.yml accordingly.

**Review by BirmacherAkos — DISMISSED** [review]

**Review by godrei — APPROVED** [review]

**Review by godrei — CHANGES_REQUESTED** [review]
@richard-bogdan-bitrise pls replace the start android emulator step with the new avd manager step may it will work better

**Comment by richard-bogdan-bitrise** [comment]
Updated to use avd manager step, however it still fails.

**Review by godrei — APPROVED** [review]

**Pull request merged**
